var map = new Datamap({
    element: document.getElementById('map-container'),
    responsive: true,
    aspectRatio: 0.13,
    projection: 'mercator',
    geographyConfig: {
      borderWidth: 0.7,
      borderColor: '#fbc360',
      highlightFillColor: '#EF48AA',
      highlightFillOpacity: 0.45,
      popupTemplate: function(geo, data) { //this function should just return a string
          return data && data.marrape_crime_label && "<div class='hoverinfo' style='font-family: Solido !important;'><strong>" + geo.properties.name + ":</strong> " + data.marrape_crime_label + "</div>"
        }
    },
    fills: {
      expresslyCriminalized: '#ec008b',
      notExplicit: '#f36f21',
      explicitlyDecriminalized: '#ed1c24',
      avoidPunishmentDecriminalized: 'url(#diagonal-stripe-red)',
      avoidPunishment: 'url(#diagonal-stripe-orange)',
      partiesSeparated: 'url(#diagonal-stripe-red-left)',
      defaultFill: '#fff5cc'
    },
    data: {
      ALB: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      ARG: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      AUS: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      BEN: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      BTN: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      BOL: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      BRA: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      BDI: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      BTN: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      CAN: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      CPV: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      CAF: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      CHL: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      COL: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      CRI: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      HRV: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      CYP: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      DOM: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      ECU: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      EST: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      FRA: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      GEO: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      GRC: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      GRD: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      GTM: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      GNB: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      GUY: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      HND: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      HUN: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      ISL: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      IRL: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      ITA: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      KOR: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      LVA: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      LUX: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      MKD: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      MDV: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      MLT: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      MEX: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      MDA: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      MNE: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      MOZ: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      NAM: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      NPL: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      NZL: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      NIC: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      PAN: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      PER: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      PHL: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      PRI: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      PRT: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      ROU: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      RWA: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      WSM: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      SMR: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      STP: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      SRB: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      SLE: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      SVK: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      SVN: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      ZAF: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      SUR: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      SWE: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      THA: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      TLS: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      TON: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      TTO: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      TUR: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      UZB: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      VEN: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      VNM: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},
      ZWE: {marrape_crime_label: 'Marital rape is expressly criminalized', fillKey: 'expresslyCriminalized'},

      AFG: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      DZA: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      ARM: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      AUT: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      AZE: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      BLR: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      BEL: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      BIH: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      BWA: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      BGR: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      BFA: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      TCD: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      CHN: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      COM: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      COD: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      COG: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      CIV: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      CZE: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      DNK: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      DJI: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      EGY: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      SLV: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      FJI: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      FIN: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      GAB: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      DEU: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      GIN: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      HTI: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      ISR: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      JPN: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      KAZ: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      KHM: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      KIR: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      KGZ: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      LBR: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      LTU: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      MDG: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      MLI: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      MHL: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      MRT: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      MUS: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      MNG: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      MAR: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      NLD: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      NER: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      NOR: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      PAK: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      PLW: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      PNG: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      PRY: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      POL: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      QAT: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      RUS: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      SAU: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      SEN: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      SYC: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      SLB: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      ESP: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      KNA: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      VCT: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      SDN: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      SWZ: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      CHE: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      TGO: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      TWN: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      UGA: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      UKR: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      ARE: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      GBR: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      USA: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      URY: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      VUT: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      YEM: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},
      ZMB: {marrape_crime_label: 'Legislation does not explicitly address marital rape as a crime', fillKey: 'notExplicit'},

      ATG: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      BHS: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      BGD: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      BRB: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      BLZ: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      BRN: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      DMA: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      GNQ: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      ETH: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      GMB: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      IDN: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      IRN: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      JAM: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      KEN: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      LAO: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      MWI: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      MYS: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      FSM: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      MMR: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      NGA: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      OMN: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      SSD: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},
      LCA: {marrape_crime_label: 'Marital rape is explicitly decriminalized', fillKey: 'explicitlyDecriminalized'},

      GHA: {marrape_crime_label: 'Marital rape only explicitly criminalized if parties separated', fillKey: 'partiesSeparated'},
      IND: {marrape_crime_label: 'Marital rape only explicitly criminalized if parties separated', fillKey: 'partiesSeparated'},
      LSO: {marrape_crime_label: 'Marital rape only explicitly criminalized if parties separated', fillKey: 'partiesSeparated'},
      SGP: {marrape_crime_label: 'Marital rape only explicitly criminalized if parties separated', fillKey: 'partiesSeparated'},
      LKA: {marrape_crime_label: 'Marital rape only explicitly criminalized if parties separated', fillKey: 'partiesSeparated'},
      TZA: {marrape_crime_label: 'Marital rape only explicitly criminalized if parties separated', fillKey: 'partiesSeparated'},

      AGO: {marrape_crime_label: 'Rapist can marry his victim to avoid punishment', fillKey: 'avoidPunishment'},
      BHR: {marrape_crime_label: 'Rapist can marry his victim to avoid punishment', fillKey: 'avoidPunishment'},
      CMR: {marrape_crime_label: 'Rapist can marry his victim to avoid punishment', fillKey: 'avoidPunishment'},
      IRQ: {marrape_crime_label: 'Rapist can marry his victim to avoid punishment', fillKey: 'avoidPunishment'},
      KWT: {marrape_crime_label: 'Rapist can marry his victim to avoid punishment', fillKey: 'avoidPunishment'},
      LBY: {marrape_crime_label: 'Rapist can marry his victim to avoid punishment', fillKey: 'avoidPunishment'},
      TJK: {marrape_crime_label: 'Rapist can marry his victim to avoid punishment', fillKey: 'avoidPunishment'},
      TUN: {marrape_crime_label: 'Rapist can marry his victim to avoid punishment', fillKey: 'avoidPunishment'},

      GNQ: {marrape_crime_label: 'Rapist can marry his victim to avoid punishment', fillKey: 'avoidPunishmentDecriminalized'},
      ERI: {marrape_crime_label: 'Rapist can marry his victim to avoid punishment', fillKey: 'avoidPunishmentDecriminalized'},
      JOR: {marrape_crime_label: 'Rapist can marry his victim to avoid punishment', fillKey: 'avoidPunishmentDecriminalized'},
      LBN: {marrape_crime_label: 'Rapist can marry his victim to avoid punishment', fillKey: 'avoidPunishmentDecriminalized'},
      SYR: {marrape_crime_label: 'Rapist can marry his victim to avoid punishment', fillKey: 'avoidPunishmentDecriminalized'},
      PSE: {marrape_crime_label: 'Rapist can marry his victim to avoid punishment', fillKey: 'avoidPunishmentDecriminalized'},

      AND: {marrape_crime_label: 'No data available'},
      ATF: {marrape_crime_label: 'No data available'},
      FLK: {marrape_crime_label: 'No data available'},
      CUB: {marrape_crime_label: 'No data available'},
      GRL: {marrape_crime_label: 'No data available'},
      GUF: {marrape_crime_label: 'No data available'},
      PRK: {marrape_crime_label: 'No data available'},
      LIE: {marrape_crime_label: 'No data available'},
      MCO: {marrape_crime_label: 'No data available'},
      NCL: {marrape_crime_label: 'No data available'},
      NRU: {marrape_crime_label: 'No data available'},
      SOM: {marrape_crime_label: 'No data available'},
      TKM: {marrape_crime_label: 'No data available'},
      TUV: {marrape_crime_label: 'No data available'},
      ESH: {marrape_crime_label: 'No data available'}

    }
});

d3.select(window).on('resize', function() {
        map.resize();
    });
